### ISSUE TITLE
Some of the constants undefined

### ISSUE THREAD

**Issue by yeesian** [visr/GDAL.jl#1]
e.g. `OGRERR_NONE`, in http://www.gdal.org/ogr__core_8h_source.html, and `GByte` from http://www.gdal.org/cpl__port_8h_source.html

**Comment by visr** [comment]
Do you think I should add these two files here? https://github.com/visr/GDAL.jl/blob/1bd4633c19bcb85ab36e8cdf974e4b25cca65f52/gen/wrap_gdal.jl#L8
Or do you only want these constants to be added to the `common.jl` file? By playing with the `header_wrapped` function I got wildly varying results, from wrapping standard libraries to nothing. I chose the minimal option at first, such that we can add anything that's missing later.

**Comment by yeesian** [comment]
might be good to branch and see; I can't tell offhand, haha

**Comment by visr** [comment]
trying to figure this out in #2
