### ISSUE TITLE
Relax function definition for createcopy

### ISSUE THREAD

**Issue by yeesian** [visr/GDAL.jl#16]
For the progress function.

Relevant lines: [here](https://github.com/visr/GDAL.jl/blob/29f75ff80ad1dc4e7ca7cce45e15aa751ea0366d/src/gdal_h.jl#L221) and [here](https://github.com/visr/GDAL.jl/blob/29f75ff80ad1dc4e7ca7cce45e15aa751ea0366d/src/C/gdal.jl#L224).

It makes it difficult to pass in vanilla `C_NULL`s into the function (e.g. in https://github.com/visr/GDAL.jl/blob/master/test/tutorial_raster.jl#L65).

**Comment by visr** [comment]
```julia
function createcopy{T <: GDALDriverH,S <: GDALDatasetH}(arg1::Ptr{T},arg2,arg3::Ptr{S},arg4::Integer,arg5,arg6::Ptr{GDALProgressFunc},arg7)
    checknull(ccall((:GDALCreateCopy,libgdal),Ptr{GDALDatasetH},(Ptr{GDALDriverH},Cstring,Ptr{GDALDatasetH},Cint,Ptr{Cstring},Ptr{GDALProgressFunc},Ptr{Void}),arg1,arg2,arg3,arg4,arg5,arg6,arg7))
end
```

In this case I believe just removing `::Ptr{GDALProgressFunc}` will suffice, right? Then it is converted to `Ptr{GDALProgressFunc}` by `ccall`. Shall I just do this for all `::Ptr{GDALProgressFunc}`? Any other types that should be relaxed like this as well?

**Comment by yeesian** [comment]
Yup, that's what I did.

> Any other types that should be relaxed like this as well?

Haha, I'm just reporting them as they come up when I'm working on [GDALUtils](https://github.com/yeesian/GDALUtils.jl/).
