### ISSUE TITLE
Enforce type consistency between the methods, and their C API

### ISSUE THREAD

**Issue by yeesian** [visr/GDAL.jl#20]
In some cases, the function in `src/ogr_api.jl` operates on `Ptr{OGRLayerH}`, whereas the corresponding C API expects `OGRLayerH`.

One specific example: https://github.com/visr/GDAL.jl/blob/master/src/ogr_api.jl#L3997-L4010 and https://github.com/visr/GDAL.jl/blob/master/src/C/ogr_api.jl#L4000-L4013

**Comment by visr** [comment]
Does this still apply, or should it be closed?

**Comment by yeesian** [comment]
I'd recommend to close it for now; I can open a new issue if i come across it.
