### ISSUE TITLE
Regenerate documentation for C API

### ISSUE THREAD

**Issue by yeesian** [visr/GDAL.jl#32]
It seems some of them have been updated include more information that was previously only available for their C++ counterparts.

**Comment by visr** [comment]
Ha, I tried regenerating the documentation (2.1.0 to 2.1.1), but the diff was pretty mild:
```diff
-    GDALAllRegister(void) -> void
+    GDALAllRegister() -> void
```
Do you have particular examples? Could be that the changes are in elements of the XML that we are currently not using.

**Comment by yeesian** [comment]
Sorry I can't remember. I'll re-open another issue if need be.
