### ISSUE TITLE
Maybe consider switching to Enums?

### ISSUE THREAD

**Issue by yeesian** [visr/GDAL.jl#35]
For reference: https://github.com/yeesian/ArchGDAL.jl/blob/master/src/types.jl#L21-L374

**Comment by yeesian** [comment]
Edit: nvm, just remembered that some of their enums map to the same value.

**Comment by visr** [comment]
This may also be more of a Clang.jl issue, see for instance the PR 162.

By the way, when linking to line numbers, it's convenient to press y on your keyboard to include the commit in the link. Was just checking some of the older issues, where the example had moved to a different location.

**Comment by yeesian** [comment]
👌
