### ISSUE TITLE
Should we wrap cpl_conv?

### ISSUE THREAD

**Issue by yeesian** [visr/GDAL.jl#36]
relevant header file: http://www.gdal.org/cpl__conv_8h.html

I noticed it from https://trac.osgeo.org/gdal/wiki/ConfigOptions.

**Comment by yeesian** [comment]
See how it's used in: https://github.com/yeesian/ArchGDAL.jl/pull/7

**Comment by visr** [comment]
Most of the functions in cpl_conv seem unneccesary for us.
Perhaps only copy over the functions you wrapped already?
Or wrap them automatically but only a short whitelist.
